[package]
name = "aptos_hash"
version = "1.0.0"

[addresses]
aptos_std = "0x1"

[dependencies]
MoveStdlib = { git = "https://github.com/move-language/move-on-aptos.git", subdir = "language/move-stdlib", rev = "main", addr_subst = { "std" = "0x1" } }
# AptosStdLib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib", rev = "aptos-release-v1.38", addr_subst = { "std" = "0x1" } }
AptosStdLib = { local = "../../../aptos-core/aptos-move/framework/aptos-stdlib/", addr_subst = { "aptos_std" = "0x1" } }
