[package]
name = "taohe"

[addresses]
TaoHe = "0x2f66c09143acc52a85fec529a4e20c85"
Connector = "0x2f66c09143acc52a85fec529a4e20c85"

[dependencies]
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", rev = "c1f1ae650fb9f9248b39a569400b4420820868db", subdir = "crates/sui-framework/packages/move-stdlib" }
TaoHe = { git = "https://github.com/taoheorg/taohe.git", rev = "main" }
Connector = { git = "https://github.com/taoheorg/connector-dummy.git", rev = "2125806ade4a1b0995c370524e69c7c3a864724e" }
