[package]
name = "storage"

[addresses]
std = "0x1"
owner = "0xab010101010101010101010101010101010101010101010101010101010101ce"
alice = "0x7da26da5e784569ae3cd4c8558852c82d69fa904bd1a14611cd3fd15c79335d4"

[dependencies]
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", rev = "c1f1ae650fb9f9248b39a569400b4420820868db", subdir = "crates/sui-framework/packages/move-stdlib" }
