[package]
name = "UnitTest"

[addresses]
UnitTest = "0xba31"

[dependencies]
# MoveStdlib = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "move-stdlib", rev = "main", addr_subst = { "std" = "0x1" } }
MoveStdlib = { local = "../../../sui/crates/sui-framework/packages/move-stdlib" }
