[package]
name = "CoinSwap"

[addresses]
std = "0x1"
CoinSwap = "0xC5"
BasicCoin = "0xBC"
GoldCoin = "0x9C"
SilverCoin = "0x5C"

[dependencies]
BasicCoin = { local = "../basic-coin" }
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", rev = "c1f1ae650fb9f9248b39a569400b4420820868db", subdir = "crates/sui-framework/packages/move-stdlib" }
