[package]
name = "multi_module"
version = "1.0.0"

[addresses]
multi_module = "0x7"
std = "0x1"

[dependencies]
MoveStdlib = { git = "https://github.com/move-language/move-on-aptos.git", subdir = "language/move-stdlib", rev = "main" }
