[package]
name = "multi_module"

[addresses]
multi_module = "0x7"

[dependencies]
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", rev = "c1f1ae650fb9f9248b39a569400b4420820868db", subdir = "crates/sui-framework/packages/move-stdlib" }
