[package]
name = "objects"

[dependencies]
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", rev = "c1f1ae650fb9f9248b39a569400b4420820868db", subdir = "crates/sui-framework/packages/move-stdlib" }

[addresses]
std = "0x1"
objects = "0x2"
