[package]
name = "objects"

[dependencies]
MoveStdlib = { git = "https://github.com/move-language/move-on-aptos.git", subdir = "language/move-stdlib", rev = "main", addr_subst = { "std" = "0x1" } }

[addresses]
std = "0x1"
objects = "0x2"
