[package]
name = "void"
version = "1.0.0"

[addresses]
std = "0x1"

[dependencies]
MoveStdlib = { git = "https://github.com/move-language/move-on-aptos.git", subdir = "language/move-stdlib", rev = "main" }
# storage = { local = "../storage" }
